[build]
  command = "npm install"
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]
  included_files = ["config/**", "models/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://infinite112.netlify.app"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Max-Age = "86400"

[[headers]]
  for = "/.netlify/functions/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://infinite112.netlify.app"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Max-Age = "86400"
