[build]
  command = "npm install"
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]
  included_files = ["config/**", "models/**"]

[[redirects]]
  from = "/.netlify/functions/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "https://infinite112.netlify.app"}

[[headers]]
  for = "/.netlify/functions/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://infinite112.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
